In [61]:
import pandas as pd
import numpy as np
import seaborn as sbn

In [62]:
sam = pd.read_csv('Movie_Data.csv')
sam.head()

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
0,The Dark Knight,2008.0,PG-13,152.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://imdb-video.media-imdb.com/vi324468761/...,"Action, Crime, Drama",9.0,2800000.0,United States,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,185000000.0,1.029266e+09
1,The Lord of the Rings: The Return of the King,2003.0,PG-13,201.0,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,https://imdb-video.media-imdb.com/vi718127897/...,"Action, Adventure, Drama",9.0,1900000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",Gandalf and Aragorn lead the World of Men agai...,94000000.0,1.155871e+09
2,Dr. Babasaheb Ambedkar,2000.0,3h 17m,197.0,https://m.media-amazon.com/images/M/MV5BNGNjZD...,https://imdb-video.media-imdb.com/vi2344205849...,"Biography, History",8.9,2700.0,India,Jabbar Patel,"Daya Pawar, Arun Sadhu, Sooni Taraporevala","Mammootty, Sonali Kulkarni, Mohan Gokhale, Mri...","Biopic of B. R. Ambedkar, known mainly for his...",NaN,NaN
3,The Lord of the Rings: The Fellowship of the Ring,2001.0,PG-13,178.0,https://m.media-amazon.com/images/M/MV5BN2EyZj...,https://imdb-video.media-imdb.com/vi684573465/...,"Action, Adventure, Drama",8.8,2000000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",A meek Hobbit from the Shire and eight compani...,93000000.0,8.985237e+08
4,The Lord of the Rings: The Two Towers,2002.0,PG-13,179.0,https://m.media-amazon.com/images/M/MV5BZGMxZT...,https://imdb-video.media-imdb.com/vi701350681/...,"Action, Adventure, Drama",8.8,1700000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",While Frodo and Sam edge closer to Mordor with...,94000000.0,9.488931e+08

In [63]:
manh = pd.read_csv('movies.csv')
for i in ['Genre', 'Country', 'Director', 'Writer', 'Stars']:
    manh[i] = manh[i].str[1:-1].str.replace("'", "")

In [64]:
phu = pd.read_csv('Movie_data_phu.csv')
for i in ['Genre', 'Country', 'Director', 'Writer', 'Stars']:
    phu[i] = phu[i].str[1:-1].str.replace("'", "")
phu.head()

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Story,Budget,Gross US & Canada,Opening weekend US & Canada,Gross worldwide,Cost,Income
0,The Hunger Games,2012,6+,142.0,https://m.media-amazon.com/images/M/MV5BMjA4ND...,https://www.imdb.com/video/vi37406489/,"Action, Adventure, Sci-Fi",7.2,972675,United States,Gary Ross,"Gary Ross, Suzanne Collins, Billy Ray","Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",Katniss Everdeen voluntarily takes her younger...,"$78,000,000 (estimated)","$408,010,692","$152,535,747","$695,220,619","$78,000,000 (estimated)","$695,220,619"
1,The Hunger Games: Catching Fire,2013,6+,146.0,https://m.media-amazon.com/images/M/MV5BMTAyMj...,https://www.imdb.com/video/vi37406489/,"Action, Adventure, Sci-Fi",7.5,700519,United States,Francis Lawrence,"Simon Beaufoy, Michael Arndt, Suzanne Collins","Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",Katniss Everdeen and Peeta Mellark become targ...,"$130,000,000 (estimated)","$424,668,047","$158,074,286","$865,011,746","$130,000,000 (estimated)","$865,011,746"
2,Scott Pilgrim vs. the World,2010,PG-12,112.0,https://m.media-amazon.com/images/M/MV5BNWI5OD...,https://www.imdb.com/video/vi4036739097/,"Action, Comedy, Fantasy",7.5,454254,"United States, United Kingdom, Canada, Japan",Edgar Wright,"Michael Bacall, Edgar Wright, Bryan Lee O&apos...","Michael Cera, Mary Elizabeth Winstead, Kieran ...","In a magically realistic version of Toronto, a...","$60,000,000 (estimated)","$33,281,690","$10,609,795","$49,421,974","$60,000,000 (estimated)","$49,421,974"
3,Lo imposible,2013,PG-13,114.0,https://m.media-amazon.com/images/M/MV5BMWFjZD...,https://www.imdb.com/video/vi118006809/,"Drama, History, Thriller",7.5,236968,"Spain, Thailand, United States",J.A. Bayona,"Sergio G. Sánchez, María Belón","Naomi Watts, Ewan McGregor, Tom Holland",The story of a tourist family in Thailand caug...,"$45,000,000 (estimated)","$19,019,882","$143,818","$198,087,212","$45,000,000 (estimated)","$198,087,212"
4,The Wolf of Wall Street,2014,R-18,180.0,https://m.media-amazon.com/images/M/MV5BMjIxMj...,https://www.imdb.com/video/vi2312218649/,"Biography, Comedy, Crime",8.2,1529292,United States,Martin Scorsese,"Terence Winter, Jordan Belfort","Leonardo DiCaprio, Jonah Hill, Margot Robbie","Based on the true story of Jordan Belfort, fro...","$100,000,000 (estimated)","$116,900,694","$18,361,578","$406,878,233","$100,000,000 (estimated)","$406,878,233"

In [65]:
vanh = pd.read_csv('Movie_Data1.csv', names=sam.columns)
vanh.head()

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
0,Uruttu Tech,2023.0,1h 6m,66.0,https://m.media-amazon.com/images/M/MV5BYjIwMD...,NaN,Comedy,9.7,8400.0,India,NaN,NaN,NaN,The tech war between truth and deception begin...,NaN,NaN
1,Spark: L.I.F.E.,2023.0,2h 50m,170.0,https://m.media-amazon.com/images/M/MV5BMjRmNj...,https://imdb-video.media-imdb.com/vi3502622489...,"Action, Romance, Thriller",9.6,2000.0,India,Vikranth Reddy,"Umarji Anuradha, Mahesh, Vikranth Reddy","Vikranth Reddy, Mehreen Pirzada, Rukshar Dhill...",Jay's love for Ananya leads to a deadly chain ...,NaN,NaN
2,Mandali,2023.0,1h 58m,118.0,https://m.media-amazon.com/images/M/MV5BYmRiYT...,https://imdb-video.media-imdb.com/vi3687171865...,Drama,9.6,1100.0,India,Rakesh Chaturvedi Om,"Vinay Agrahari, Pallav Jain, Rakesh Chaturvedi Om","Alka Amin, Mark Arvind, Ashwath Bhatt, Rajnees...",It mirrors the journey of a man and his strugg...,NaN,NaN
3,Behind Closed Doors,2023.0,1h 4m,64.0,https://m.media-amazon.com/images/M/MV5BY2I2Yz...,NaN,Documentary,9.5,1400.0,United Kingdom,Michael Oswald,"Murtaza Mehdi, Michael Oswald","Mirza Shahzad Akbar, Fawad Chaudry, Irfan Hash...",Politically Exposed Persons (PEPs) are people ...,NaN,NaN
4,Yesterday's Past,2021.0,1h 23m,83.0,https://m.media-amazon.com/images/M/MV5BZTZlOW...,NaN,Drama,9.5,3100.0,India,Nila Madhab Panda,Nila Madhab Panda,"Pitobash, Sonalli Sharmisstha",A man returns to his home village hoping to re...,NaN,NaN

In [66]:
sam.columns[~sam.columns.isin(manh.columns)]

Index(['Storyline', 'Cost', 'Income'], dtype='object')

In [67]:
manh.columns.isin(sam.columns)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False])

In [68]:
sam_vanh = pd.concat([sam, vanh])
sam_vanh.head()

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
0,The Dark Knight,2008.0,PG-13,152.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://imdb-video.media-imdb.com/vi324468761/...,"Action, Crime, Drama",9.0,2800000.0,United States,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,185000000.0,1.029266e+09
1,The Lord of the Rings: The Return of the King,2003.0,PG-13,201.0,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,https://imdb-video.media-imdb.com/vi718127897/...,"Action, Adventure, Drama",9.0,1900000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",Gandalf and Aragorn lead the World of Men agai...,94000000.0,1.155871e+09
2,Dr. Babasaheb Ambedkar,2000.0,3h 17m,197.0,https://m.media-amazon.com/images/M/MV5BNGNjZD...,https://imdb-video.media-imdb.com/vi2344205849...,"Biography, History",8.9,2700.0,India,Jabbar Patel,"Daya Pawar, Arun Sadhu, Sooni Taraporevala","Mammootty, Sonali Kulkarni, Mohan Gokhale, Mri...","Biopic of B. R. Ambedkar, known mainly for his...",NaN,NaN
3,The Lord of the Rings: The Fellowship of the Ring,2001.0,PG-13,178.0,https://m.media-amazon.com/images/M/MV5BN2EyZj...,https://imdb-video.media-imdb.com/vi684573465/...,"Action, Adventure, Drama",8.8,2000000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",A meek Hobbit from the Shire and eight compani...,93000000.0,8.985237e+08
4,The Lord of the Rings: The Two Towers,2002.0,PG-13,179.0,https://m.media-amazon.com/images/M/MV5BZGMxZT...,https://imdb-video.media-imdb.com/vi701350681/...,"Action, Adventure, Drama",8.8,1700000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",While Frodo and Sam edge closer to Mordor with...,94000000.0,9.488931e+08

In [69]:
sam.columns

Index(['Name', 'Release Year', 'Certificate', 'Duration', 'Poster', 'Trailer',
       'Genre', 'Rating', 'Rating Count', 'Country', 'Director', 'Writer',
       'Stars', 'Storyline', 'Cost', 'Income'],
      dtype='object')

In [70]:
manh.columns

Index(['Name', 'Release Year', 'Certificate', 'Duration', 'Poster', 'Trailer',
       'Genre', 'Rating', 'Rating Count', 'Country', 'Director', 'Writer',
       'Stars', 'Story', 'Budget', 'Gross US & Canada',
       'Opening weekend US & Canada', 'Gross worldwide'],
      dtype='object')

In [71]:
manh['Cost'] = manh['Budget']
manh['Storyline'] = manh['Story']
manh['Income'] = manh['Gross worldwide']

In [72]:
manh = manh[manh.columns[manh.columns.isin(sam.columns)]]

In [73]:
sam_vanh_manh = pd.concat([sam_vanh, manh])
sam_vanh_manh.head()

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
0,The Dark Knight,2008.0,PG-13,152.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://imdb-video.media-imdb.com/vi324468761/...,"Action, Crime, Drama",9.0,2800000.0,United States,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,185000000.0,1029266147.0
1,The Lord of the Rings: The Return of the King,2003.0,PG-13,201.0,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,https://imdb-video.media-imdb.com/vi718127897/...,"Action, Adventure, Drama",9.0,1900000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",Gandalf and Aragorn lead the World of Men agai...,94000000.0,1155870721.0
2,Dr. Babasaheb Ambedkar,2000.0,3h 17m,197.0,https://m.media-amazon.com/images/M/MV5BNGNjZD...,https://imdb-video.media-imdb.com/vi2344205849...,"Biography, History",8.9,2700.0,India,Jabbar Patel,"Daya Pawar, Arun Sadhu, Sooni Taraporevala","Mammootty, Sonali Kulkarni, Mohan Gokhale, Mri...","Biopic of B. R. Ambedkar, known mainly for his...",NaN,NaN
3,The Lord of the Rings: The Fellowship of the Ring,2001.0,PG-13,178.0,https://m.media-amazon.com/images/M/MV5BN2EyZj...,https://imdb-video.media-imdb.com/vi684573465/...,"Action, Adventure, Drama",8.8,2000000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",A meek Hobbit from the Shire and eight compani...,93000000.0,898523656.0
4,The Lord of the Rings: The Two Towers,2002.0,PG-13,179.0,https://m.media-amazon.com/images/M/MV5BZGMxZT...,https://imdb-video.media-imdb.com/vi701350681/...,"Action, Adventure, Drama",8.8,1700000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",While Frodo and Sam edge closer to Mordor with...,94000000.0,948893109.0

In [74]:
sam.columns[~sam.columns.isin(phu.columns)]

Index(['Storyline'], dtype='object')

In [75]:
phu.columns

Index(['Name', 'Release Year', 'Certificate', 'Duration', 'Poster', 'Trailer',
       'Genre', 'Rating', 'Rating Count', 'Country', 'Director', 'Writer',
       'Stars', 'Story', 'Budget', 'Gross US & Canada',
       'Opening weekend US & Canada', 'Gross worldwide', 'Cost', 'Income'],
      dtype='object')

In [76]:
phu['Storyline'] = phu['Story']

In [77]:
sam.columns[~sam.columns.isin(phu.columns)]

Index([], dtype='object')

In [78]:
phu = phu[phu.columns[phu.columns.isin(sam.columns)]]

In [79]:
data = pd.concat([sam_vanh_manh, phu])
data

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
0,The Dark Knight,2008.0,PG-13,152.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://imdb-video.media-imdb.com/vi324468761/...,"Action, Crime, Drama",9.0,2800000.0,United States,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,185000000.0,1029266147.0
1,The Lord of the Rings: The Return of the King,2003.0,PG-13,201.0,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,https://imdb-video.media-imdb.com/vi718127897/...,"Action, Adventure, Drama",9.0,1900000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",Gandalf and Aragorn lead the World of Men agai...,94000000.0,1155870721.0
2,Dr. Babasaheb Ambedkar,2000.0,3h 17m,197.0,https://m.media-amazon.com/images/M/MV5BNGNjZD...,https://imdb-video.media-imdb.com/vi2344205849...,"Biography, History",8.9,2700.0,India,Jabbar Patel,"Daya Pawar, Arun Sadhu, Sooni Taraporevala","Mammootty, Sonali Kulkarni, Mohan Gokhale, Mri...","Biopic of B. R. Ambedkar, known mainly for his...",NaN,NaN
3,The Lord of the Rings: The Fellowship of the Ring,2001.0,PG-13,178.0,https://m.media-amazon.com/images/M/MV5BN2EyZj...,https://imdb-video.media-imdb.com/vi684573465/...,"Action, Adventure, Drama",8.8,2000000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",A meek Hobbit from the Shire and eight compani...,93000000.0,898523656.0
4,The Lord of the Rings: The Two Towers,2002.0,PG-13,179.0,https://m.media-amazon.com/images/M/MV5BZGMxZT...,https://imdb-video.media-imdb.com/vi701350681/...,"Action, Adventure, Drama",8.8,1700000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",While Frodo and Sam edge closer to Mordor with...,94000000.0,948893109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6432,The Lives of Mount Druitt Youth,2010.0,NaN,60.0,https://m.media-amazon.com/images/M/MV5BMTI4MT...,NaN,"Documentary, Drama",4.8,1531.0,Australia,Saad Adam,,"Drew Pearson, Saad Adam, Evan Adam",Come with Saad as he visits Mount Druitt &amp;...,NaN,NaN
6433,Hich,2010.0,NaN,84.0,https://m.media-amazon.com/images/M/MV5BYTY0Y2...,NaN,"Comedy, Drama",6.8,1128.0,Iran,Abdolreza Kahani,"Abdolreza Kahani, Hossein Mahkam","Ahmad Mehranfar, Mehran Ahmadi, Nayereh Farahani","A man, who has some kind of a disease and eats...",NaN,NaN
6434,Kummeli Alivuokralainen,2008.0,NaN,104.0,https://m.media-amazon.com/images/M/MV5BODI2MD...,NaN,Comedy,4.3,1398.0,Finland,Matti Grönberg,"Timo Kahilainen, Heikki Vihinen, Anttu Harlin","Mikko Kivinen, Heikki Silvennoinen, Timo Kahil...","A farce about blackmailing, a kidney transplan...","€1,300,000 (estimated)",NaN
6435,Någon Annanstans,2009.0,NaN,87.0,https://m.media-amazon.com/images/M/MV5BMjA0Nz...,NaN,"Drama, Romance",4.4,3333.0,Sweden,Hiwa Abbasi,Hiwa Abbasi,"Ruth Anianson, Arefeh Behbakht, Lina Burström","Said, the main character in the film Another P...","$30,000 (estimated)",NaN
6436,Chambaili,2013.0,NaN,133.0,https://m.media-amazon.com/images/M/MV5BMTYxND...,NaN,"Crime, Drama, Thriller",7.7,1115.0,Pakistan,Ismail Jillani,Shahzad Nawaz,"Khalid Ahmed, Shafqat Cheema, Ehteshamuddin",A group of friends are led by circumstances to...,"$110,000 (estimated)","$12,296"

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24218 entries, 0 to 6436
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          24215 non-null  object
 1   Release Year  24190 non-null  float64
 2   Certificate   20813 non-null  object
 3   Duration      24121 non-null  float64
 4   Poster        24210 non-null  object
 5   Trailer       15927 non-null  object
 6   Genre         24207 non-null  object
 7   Rating        24211 non-null  float64
 8   Rating Count  24211 non-null  float64
 9   Country       24190 non-null  object
 10  Director      24179 non-null  object
 11  Writer        23852 non-null  object
 12  Stars         24159 non-null  object
 13  Storyline     24160 non-null  object
 14  Cost          9286 non-null   object
 15  Income        17360 non-null  object
dtypes: float64(4), object(12)
memory usage: 3.1+ MB

In [81]:
data[(data['Name'].isnull()) | (data['Poster'].isnull()) | (data['Storyline'].isnull())]

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
2744,Married for 7 Years,2003.0,1h 37m,97.0,https://m.media-amazon.com/images/M/MV5BMTI3MT...,https://imdb-video.media-imdb.com/vi477805081/...,Comedy,5.9,1100.0,France,Didier Bourdon,"Didier Bourdon, Dominique Coubes, Nathalie Vierne","Catherine Frot, Didier Bourdon, Jacques Weber,...",NaN,7870000.0,10278225.0
2757,NaN,NaN,NaN,NaN,NaN,https://imdb-video.media-imdb.com/vi614250009/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5092,Backroads,1997.0,1h 45m,105.0,https://m.media-amazon.com/images/M/MV5BMzE0OT...,https://imdb-video.media-imdb.com/vi2207827737...,"Drama, Romance",6.0,1000.0,Spain,Emilio Martínez Lázaro,Ignacio Martínez de Pisón,"Antonio Resines, Fernando Ramallo, Maribel Ver...",NaN,NaN,NaN
5225,Barbie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sweden,NaN,NaN,NaN,NaN,NaN,NaN
11,Salman Society,2023.0,NaN,NaN,https://m.media-amazon.com/images/M/MV5BZDEwNz...,https://imdb-video.media-imdb.com/vi3324299033...,Drama,9.2,1500.0,India,Kailash Kashinath Pawar,Kailash Kashinath Pawar,"Namrata Awate Sambherao, Tejas Bane, Devaki Bh...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5898,Sveti Georgije ubiva azdahu,2009.0,NaN,120.0,https://m.media-amazon.com/images/M/MV5BZWNlYz...,https://www.imdb.com/video/vi1717944601/,"Drama, History, Romance",6.4,1843.0,"Serbia, Bosnia and Herzegovina, Bulgaria",Srdjan Dragojevic,Dusan Kovacevic,"Lazar Ristovski, Natasa Janjic Medancic, Bora ...",NaN,NaN,"$325,265"
5916,Otto&apos;s Eleven,2009.0,NaN,95.0,https://m.media-amazon.com/images/M/MV5BZTBiMm...,NaN,"Comedy, Family, Mystery",4.6,1390.0,"Germany, Brazil, United States, United Kingdom",Sven Unterwaldt Jr.,"Bernd Eilert, Sven Unterwaldt Jr., Otto Waalkes","Otto Waalkes, Mirco Nontschew, Rick Kavanian",NaN,NaN,"$8,184,947"
5974,La peggior settimana della mia vita,2011.0,NaN,93.0,https://m.media-amazon.com/images/M/MV5BNTI0Yz...,https://www.imdb.com/video/vi512605209/,Comedy,5.7,1264.0,Italy,Alessandro Genovesi,"Fabio De Luigi, Alessandro Genovesi","Fabio De Luigi, Cristiana Capotondi, Monica Gu...",NaN,NaN,"$16,454,499"
6401,Männersache,2009.0,NaN,90.0,https://m.media-amazon.com/images/M/MV5BMTY3Nz...,https://www.imdb.com/video/vi2306212633/,Comedy,3.6,1036.0,Germany,"Gernot Roll, Mario Barth","Mario Barth, Dieter Tappert","Mario Barth, Dieter Tappert, Anja Kling",NaN,NaN,"$17,251,261"
6415,Kummeli V,2014.0,NaN,102.0,https://m.media-amazon.com/images/M/MV5BMjM2Nz...,NaN,"Adventure, Comedy, Sci-Fi",4.7,1123.0,Finland,Aleksi Mäkelä,"Timo Kahilainen, Heikki Silvennoinen, Heikki V...","Timo Kahilainen, Heikki Vihinen, Heikki Hela",NaN,"€1,600,000 (estimated)","$2,382,008"

In [82]:
data = data.reset_index()

In [83]:
data = data[data.columns[~data.columns.isin(['index'])]]

In [84]:
data['Certificate'][data['Certificate'].isnull()] = '1'
data['Certificate'][data['Certificate'].str.contains('h')] = np.nan
data['Certificate'][data['Certificate'] == '1'] = np.nan
data['Certificate'][data['Certificate'].isnull()] = 'Unrated'

C:\Users\buisa\AppData\Local\Temp\ipykernel_9388\976842216.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Certificate'][data['Certificate'].str.contains('h')] = np.nan
C:\Users\buisa\AppData\Local\Temp\ipykernel_9388\976842216.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Certificate'][data['Certificate'] == '1'] = np.nan
C:\Users\buisa\AppData\Local\Temp\ipykernel_9388\976842216.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Certificate'][data['Certificate'].isnull()] = 'Unrated'

In [85]:
data

,Name,Release Year,Certificate,Duration,Poster,Trailer,Genre,Rating,Rating Count,Country,Director,Writer,Stars,Storyline,Cost,Income
0,The Dark Knight,2008.0,PG-13,152.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://imdb-video.media-imdb.com/vi324468761/...,"Action, Crime, Drama",9.0,2800000.0,United States,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,185000000.0,1029266147.0
1,The Lord of the Rings: The Return of the King,2003.0,PG-13,201.0,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,https://imdb-video.media-imdb.com/vi718127897/...,"Action, Adventure, Drama",9.0,1900000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",Gandalf and Aragorn lead the World of Men agai...,94000000.0,1155870721.0
2,Dr. Babasaheb Ambedkar,2000.0,Unrated,197.0,https://m.media-amazon.com/images/M/MV5BNGNjZD...,https://imdb-video.media-imdb.com/vi2344205849...,"Biography, History",8.9,2700.0,India,Jabbar Patel,"Daya Pawar, Arun Sadhu, Sooni Taraporevala","Mammootty, Sonali Kulkarni, Mohan Gokhale, Mri...","Biopic of B. R. Ambedkar, known mainly for his...",NaN,NaN
3,The Lord of the Rings: The Fellowship of the Ring,2001.0,PG-13,178.0,https://m.media-amazon.com/images/M/MV5BN2EyZj...,https://imdb-video.media-imdb.com/vi684573465/...,"Action, Adventure, Drama",8.8,2000000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",A meek Hobbit from the Shire and eight compani...,93000000.0,898523656.0
4,The Lord of the Rings: The Two Towers,2002.0,PG-13,179.0,https://m.media-amazon.com/images/M/MV5BZGMxZT...,https://imdb-video.media-imdb.com/vi701350681/...,"Action, Adventure, Drama",8.8,1700000.0,New Zealand,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",While Frodo and Sam edge closer to Mordor with...,94000000.0,948893109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24213,The Lives of Mount Druitt Youth,2010.0,Unrated,60.0,https://m.media-amazon.com/images/M/MV5BMTI4MT...,NaN,"Documentary, Drama",4.8,1531.0,Australia,Saad Adam,,"Drew Pearson, Saad Adam, Evan Adam",Come with Saad as he visits Mount Druitt &amp;...,NaN,NaN
24214,Hich,2010.0,Unrated,84.0,https://m.media-amazon.com/images/M/MV5BYTY0Y2...,NaN,"Comedy, Drama",6.8,1128.0,Iran,Abdolreza Kahani,"Abdolreza Kahani, Hossein Mahkam","Ahmad Mehranfar, Mehran Ahmadi, Nayereh Farahani","A man, who has some kind of a disease and eats...",NaN,NaN
24215,Kummeli Alivuokralainen,2008.0,Unrated,104.0,https://m.media-amazon.com/images/M/MV5BODI2MD...,NaN,Comedy,4.3,1398.0,Finland,Matti Grönberg,"Timo Kahilainen, Heikki Vihinen, Anttu Harlin","Mikko Kivinen, Heikki Silvennoinen, Timo Kahil...","A farce about blackmailing, a kidney transplan...","€1,300,000 (estimated)",NaN
24216,Någon Annanstans,2009.0,Unrated,87.0,https://m.media-amazon.com/images/M/MV5BMjA0Nz...,NaN,"Drama, Romance",4.4,3333.0,Sweden,Hiwa Abbasi,Hiwa Abbasi,"Ruth Anianson, Arefeh Behbakht, Lina Burström","Said, the main character in the film Another P...","$30,000 (estimated)",NaN
24217,Chambaili,2013.0,Unrated,133.0,https://m.media-amazon.com/images/M/MV5BMTYxND...,NaN,"Crime, Drama, Thriller",7.7,1115.0,Pakistan,Ismail Jillani,Shahzad Nawaz,"Khalid Ahmed, Shafqat Cheema, Ehteshamuddin",A group of friends are led by circumstances to...,"$110,000 (estimated)","$12,296"

In [86]:
data2 = data[['Name', 'Certificate', 'Poster', 'Genre', 'Director', 'Writer', 'Stars', 'Storyline', 'Rating', 'Rating Count']]

In [87]:
data2

,Name,Certificate,Poster,Genre,Director,Writer,Stars,Storyline,Rating,Rating Count
0,The Dark Knight,PG-13,https://m.media-amazon.com/images/M/MV5BMTMxNT...,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,9.0,2800000.0
1,The Lord of the Rings: The Return of the King,PG-13,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,"Action, Adventure, Drama",Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",Gandalf and Aragorn lead the World of Men agai...,9.0,1900000.0
2,Dr. Babasaheb Ambedkar,Unrated,https://m.media-amazon.com/images/M/MV5BNGNjZD...,"Biography, History",Jabbar Patel,"Daya Pawar, Arun Sadhu, Sooni Taraporevala","Mammootty, Sonali Kulkarni, Mohan Gokhale, Mri...","Biopic of B. R. Ambedkar, known mainly for his...",8.9,2700.0
3,The Lord of the Rings: The Fellowship of the Ring,PG-13,https://m.media-amazon.com/images/M/MV5BN2EyZj...,"Action, Adventure, Drama",Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",A meek Hobbit from the Shire and eight compani...,8.8,2000000.0
4,The Lord of the Rings: The Two Towers,PG-13,https://m.media-amazon.com/images/M/MV5BZGMxZT...,"Action, Adventure, Drama",Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens","Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",While Frodo and Sam edge closer to Mordor with...,8.8,1700000.0
...,...,...,...,...,...,...,...,...,...,...
24213,The Lives of Mount Druitt Youth,Unrated,https://m.media-amazon.com/images/M/MV5BMTI4MT...,"Documentary, Drama",Saad Adam,,"Drew Pearson, Saad Adam, Evan Adam",Come with Saad as he visits Mount Druitt &amp;...,4.8,1531.0
24214,Hich,Unrated,https://m.media-amazon.com/images/M/MV5BYTY0Y2...,"Comedy, Drama",Abdolreza Kahani,"Abdolreza Kahani, Hossein Mahkam","Ahmad Mehranfar, Mehran Ahmadi, Nayereh Farahani","A man, who has some kind of a disease and eats...",6.8,1128.0
24215,Kummeli Alivuokralainen,Unrated,https://m.media-amazon.com/images/M/MV5BODI2MD...,Comedy,Matti Grönberg,"Timo Kahilainen, Heikki Vihinen, Anttu Harlin","Mikko Kivinen, Heikki Silvennoinen, Timo Kahil...","A farce about blackmailing, a kidney transplan...",4.3,1398.0
24216,Någon Annanstans,Unrated,https://m.media-amazon.com/images/M/MV5BMjA0Nz...,"Drama, Romance",Hiwa Abbasi,Hiwa Abbasi,"Ruth Anianson, Arefeh Behbakht, Lina Burström","Said, the main character in the film Another P...",4.4,3333.0
24217,Chambaili,Unrated,https://m.media-amazon.com/images/M/MV5BMTYxND...,"Crime, Drama, Thriller",Ismail Jillani,Shahzad Nawaz,"Khalid Ahmed, Shafqat Cheema, Ehteshamuddin",A group of friends are led by circumstances to...,7.7,1115.0

In [88]:
mask = ~data2['Name'].isnull()
for i in data2.columns:
    mask = (mask & ~data2[i].isnull())
data2 = data2[mask]

In [89]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23778 entries, 0 to 24217
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          23778 non-null  object
 1   Certificate   23778 non-null  object
 2   Poster        23778 non-null  object
 3   Genre         23778 non-null  object
 4   Director      23778 non-null  object
 5   Writer        23778 non-null  object
 6   Stars         23778 non-null  object
 7   Storyline     23778 non-null  object
 8   Rating        23778 non-null  float64
 9   Rating Count  23778 non-null  float64
dtypes: float64(2), object(8)
memory usage: 2.0+ MB

In [90]:
data.to_csv('Full_Raw_Data.csv')
data2.to_csv('Cleaned_Data.csv')

In [149]:
data['Genre'].str[1:-1]

0                  ction, Crime, Dram
1              ction, Adventure, Dram
2                    iography, Histor
3              ction, Adventure, Dram
4              ction, Adventure, Dram
                     ...
24213          'Documentary', 'Drama'
24214               'Comedy', 'Drama'
24215                        'Comedy'
24216              'Drama', 'Romance'
24217    'Crime', 'Drama', 'Thriller'
Name: Genre, Length: 24218, dtype: object